import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/Providers/theme-providers";
import { cn } from "@/lib/utils";
import { ModalProvider } from "@/components/Providers/modal-providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={cn(inter.className,
          "bg-white dark:bg-[#2c2c2c]") }>
          <ThemeProvider
          attribute='class'
          defaultTheme="dark"
          enableSystem
          storageKey="discordTheme"
          >
            <ModalProvider/>

          {children}
            {/* </ModalProvider> */}
          </ThemeProvider>
          </body>
      </html>
    </ClerkProvider>
  );
}
