import { Inter } from "next/font/google";
import "../globals.css";
// import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
   
   <div className="bg-slate-200 h-screen flex justify-center items-center">

        <div className={inter.className}>{children}</div>
   </div>
    
 
  );
}
